name: Build and Publish storybook to GitHub Pages

on:
  push:
    branches:
      - "main"
    pull_request:
      branches:
        [ "main" ]
    workflow_dispatch:

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.build-publish.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: npm install, build, and test
        run: |
          yarn install
          npm run build-only --if-present
      - id: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.0
        with:
          path: dist/storybook
          build_command: npm run build-storybook
